openapi: 3.0.0
info:
  title: Real-time DB Update API
  version: '1.0'
# servers:
#   - url: /api



paths:
  /data:
    post:
      summary: Add new data
      operationId: endpoints.add_data
      requestBody:
        description: Data to add
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                value:
                  type: integer
      responses:
        '200':
          description: Data added
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  value:
                    type: integer
    get:
      summary: Retrieve all data
      operationId: endpoints.get_data
      responses:
        '200':
          description: Data retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    value:
                      type: integer
